### ISSUE TITLE
<bug>vue3+vite打包报错

### ISSUE THREAD

**Issue by notlaughingzzm** [aesoper101/vue3-colorpicker#5]

**Comment by aesoper101** [comment]
你好，具体的错误信息是什么呢？我这是正常的

**Comment by aesoper101** [comment]
@notlaughingzzm 你好，具体的错误信息是什么呢？我这是正常的

**Comment by notlaughingzzm** [comment]
'effectScope' is not exported by node_modules\vue-demi\lib\index.esm.js, imported by node_modules\vue3-colorpicker\node_modules\@vueuse\shared\index.mjs

file: D:/designer-client/node_modules/vue3-colorpicker/node_modules/@vueuse/shared/index.mjs:1:64

1: import { computed, unref, watch, ref, customRef, isVue3, isRef, effectScope, getCurrentScope, onScopeDispose, shallowRef, watchSyncEffect, readonly, reactive, toRef, isVue2, toRefs as toRefs$1, getCurrentInstance, onBeforeUnmount, onMounted, nextTick, onUnmounted } from 'vue-demi';
                                                                   ^
2: 
3: function and(...args) {

error during build:
Error: 'effectScope' is not exported by node_modules\vue-demi\lib\index.esm.js, imported by node_modules\vue3-colorpicker\node_modules\@vueuse\shared\index.mjs
    at error (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:151:30)
    at Module.error (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:10015:16)    at Module.traceVariable (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:10400:29)
    at ModuleScope.findVariable (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:9171:39)
    at FunctionScope.findVariable (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:3632:38)
    at ChildScope.findVariable (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:3632:38)
    at Identifier.bind (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:4569:40)
    at CallExpression.bind (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:2884:23)
    at CallExpression.bind (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:7105:15)
    at VariableDeclarator.bind (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:2884:23)
    at VariableDeclaration.bind (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:2880:31)
    at BlockStatement.bind (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:2880:31)
    at FunctionDeclaration.bind (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:2884:23)
    at Program.bind (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:2880:31) 
    at Module.bindReferences (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:10011:18)
    at Graph.sortModules (D:\designer-client\node_modules\rollup\dist\shared\rollup.js:20402:20)
error Command failed with exit code 1.

**Comment by notlaughingzzm** [comment]
基本上这里面得大多数的东西都会提示没有导出

import { computed, unref, watch, ref, customRef, isVue3, isRef, effectScope, getCurrentScope, onScopeDispose, shallowRef, watchSyncEffect, readonly, reactive, toRef, isVue2, toRefs as toRefs$1, getCurrentInstance, onBeforeUnmount, onMounted, nextTick, onUnmounted } from 'vue-demi';

**Comment by aesoper101** [comment]
@notlaughingzzm 你看看你用的vue版本是否低于我使用的版本，我的3.2.6版本，如果低于3.2.6这个版本就会出现这个问题

**Comment by notlaughingzzm** [comment]
@aesoper101 冒昧问一下。。如何升级到3.26以上呢 我现在是3.15   
 "vue": "3.1.5",
